# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.20.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.20.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/huyduong/Downloads/Team5-Assignment2 "

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/huyduong/Downloads/Team5-Assignment2 "

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.20.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.20.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/huyduong/Downloads/Team5-Assignment2 /CMakeFiles" "/Users/huyduong/Downloads/Team5-Assignment2 //CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/huyduong/Downloads/Team5-Assignment2 /CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Team5_Assignment2_Scanner

# Build rule for target.
Team5_Assignment2_Scanner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Team5_Assignment2_Scanner
.PHONY : Team5_Assignment2_Scanner

# fast build rule for target.
Team5_Assignment2_Scanner/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Team5_Assignment2_Scanner.dir/build.make CMakeFiles/Team5_Assignment2_Scanner.dir/build
.PHONY : Team5_Assignment2_Scanner/fast

#=============================================================================
# Target rules for targets named Team5_Assignment2_Parser

# Build rule for target.
Team5_Assignment2_Parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Team5_Assignment2_Parser
.PHONY : Team5_Assignment2_Parser

# fast build rule for target.
Team5_Assignment2_Parser/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Team5_Assignment2_Parser.dir/build.make CMakeFiles/Team5_Assignment2_Parser.dir/build
.PHONY : Team5_Assignment2_Parser/fast

frontend/Parser.o: frontend/Parser.cpp.o
.PHONY : frontend/Parser.o

# target to build an object file
frontend/Parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Team5_Assignment2_Parser.dir/build.make CMakeFiles/Team5_Assignment2_Parser.dir/frontend/Parser.cpp.o
.PHONY : frontend/Parser.cpp.o

frontend/Parser.i: frontend/Parser.cpp.i
.PHONY : frontend/Parser.i

# target to preprocess a source file
frontend/Parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Team5_Assignment2_Parser.dir/build.make CMakeFiles/Team5_Assignment2_Parser.dir/frontend/Parser.cpp.i
.PHONY : frontend/Parser.cpp.i

frontend/Parser.s: frontend/Parser.cpp.s
.PHONY : frontend/Parser.s

# target to generate assembly for a file
frontend/Parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Team5_Assignment2_Parser.dir/build.make CMakeFiles/Team5_Assignment2_Parser.dir/frontend/Parser.cpp.s
.PHONY : frontend/Parser.cpp.s

frontend/Scanner.o: frontend/Scanner.cpp.o
.PHONY : frontend/Scanner.o

# target to build an object file
frontend/Scanner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Team5_Assignment2_Scanner.dir/build.make CMakeFiles/Team5_Assignment2_Scanner.dir/frontend/Scanner.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Team5_Assignment2_Parser.dir/build.make CMakeFiles/Team5_Assignment2_Parser.dir/frontend/Scanner.cpp.o
.PHONY : frontend/Scanner.cpp.o

frontend/Scanner.i: frontend/Scanner.cpp.i
.PHONY : frontend/Scanner.i

# target to preprocess a source file
frontend/Scanner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Team5_Assignment2_Scanner.dir/build.make CMakeFiles/Team5_Assignment2_Scanner.dir/frontend/Scanner.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Team5_Assignment2_Parser.dir/build.make CMakeFiles/Team5_Assignment2_Parser.dir/frontend/Scanner.cpp.i
.PHONY : frontend/Scanner.cpp.i

frontend/Scanner.s: frontend/Scanner.cpp.s
.PHONY : frontend/Scanner.s

# target to generate assembly for a file
frontend/Scanner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Team5_Assignment2_Scanner.dir/build.make CMakeFiles/Team5_Assignment2_Scanner.dir/frontend/Scanner.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Team5_Assignment2_Parser.dir/build.make CMakeFiles/Team5_Assignment2_Parser.dir/frontend/Scanner.cpp.s
.PHONY : frontend/Scanner.cpp.s

frontend/Token.o: frontend/Token.cpp.o
.PHONY : frontend/Token.o

# target to build an object file
frontend/Token.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Team5_Assignment2_Scanner.dir/build.make CMakeFiles/Team5_Assignment2_Scanner.dir/frontend/Token.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Team5_Assignment2_Parser.dir/build.make CMakeFiles/Team5_Assignment2_Parser.dir/frontend/Token.cpp.o
.PHONY : frontend/Token.cpp.o

frontend/Token.i: frontend/Token.cpp.i
.PHONY : frontend/Token.i

# target to preprocess a source file
frontend/Token.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Team5_Assignment2_Scanner.dir/build.make CMakeFiles/Team5_Assignment2_Scanner.dir/frontend/Token.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Team5_Assignment2_Parser.dir/build.make CMakeFiles/Team5_Assignment2_Parser.dir/frontend/Token.cpp.i
.PHONY : frontend/Token.cpp.i

frontend/Token.s: frontend/Token.cpp.s
.PHONY : frontend/Token.s

# target to generate assembly for a file
frontend/Token.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Team5_Assignment2_Scanner.dir/build.make CMakeFiles/Team5_Assignment2_Scanner.dir/frontend/Token.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Team5_Assignment2_Parser.dir/build.make CMakeFiles/Team5_Assignment2_Parser.dir/frontend/Token.cpp.s
.PHONY : frontend/Token.cpp.s

intermediate/TreeWalker.o: intermediate/TreeWalker.cpp.o
.PHONY : intermediate/TreeWalker.o

# target to build an object file
intermediate/TreeWalker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Team5_Assignment2_Parser.dir/build.make CMakeFiles/Team5_Assignment2_Parser.dir/intermediate/TreeWalker.cpp.o
.PHONY : intermediate/TreeWalker.cpp.o

intermediate/TreeWalker.i: intermediate/TreeWalker.cpp.i
.PHONY : intermediate/TreeWalker.i

# target to preprocess a source file
intermediate/TreeWalker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Team5_Assignment2_Parser.dir/build.make CMakeFiles/Team5_Assignment2_Parser.dir/intermediate/TreeWalker.cpp.i
.PHONY : intermediate/TreeWalker.cpp.i

intermediate/TreeWalker.s: intermediate/TreeWalker.cpp.s
.PHONY : intermediate/TreeWalker.s

# target to generate assembly for a file
intermediate/TreeWalker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Team5_Assignment2_Parser.dir/build.make CMakeFiles/Team5_Assignment2_Parser.dir/intermediate/TreeWalker.cpp.s
.PHONY : intermediate/TreeWalker.cpp.s

main_parser.o: main_parser.cpp.o
.PHONY : main_parser.o

# target to build an object file
main_parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Team5_Assignment2_Parser.dir/build.make CMakeFiles/Team5_Assignment2_Parser.dir/main_parser.cpp.o
.PHONY : main_parser.cpp.o

main_parser.i: main_parser.cpp.i
.PHONY : main_parser.i

# target to preprocess a source file
main_parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Team5_Assignment2_Parser.dir/build.make CMakeFiles/Team5_Assignment2_Parser.dir/main_parser.cpp.i
.PHONY : main_parser.cpp.i

main_parser.s: main_parser.cpp.s
.PHONY : main_parser.s

# target to generate assembly for a file
main_parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Team5_Assignment2_Parser.dir/build.make CMakeFiles/Team5_Assignment2_Parser.dir/main_parser.cpp.s
.PHONY : main_parser.cpp.s

main_scanner.o: main_scanner.cpp.o
.PHONY : main_scanner.o

# target to build an object file
main_scanner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Team5_Assignment2_Scanner.dir/build.make CMakeFiles/Team5_Assignment2_Scanner.dir/main_scanner.cpp.o
.PHONY : main_scanner.cpp.o

main_scanner.i: main_scanner.cpp.i
.PHONY : main_scanner.i

# target to preprocess a source file
main_scanner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Team5_Assignment2_Scanner.dir/build.make CMakeFiles/Team5_Assignment2_Scanner.dir/main_scanner.cpp.i
.PHONY : main_scanner.cpp.i

main_scanner.s: main_scanner.cpp.s
.PHONY : main_scanner.s

# target to generate assembly for a file
main_scanner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Team5_Assignment2_Scanner.dir/build.make CMakeFiles/Team5_Assignment2_Scanner.dir/main_scanner.cpp.s
.PHONY : main_scanner.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Team5_Assignment2_Parser"
	@echo "... Team5_Assignment2_Scanner"
	@echo "... frontend/Parser.o"
	@echo "... frontend/Parser.i"
	@echo "... frontend/Parser.s"
	@echo "... frontend/Scanner.o"
	@echo "... frontend/Scanner.i"
	@echo "... frontend/Scanner.s"
	@echo "... frontend/Token.o"
	@echo "... frontend/Token.i"
	@echo "... frontend/Token.s"
	@echo "... intermediate/TreeWalker.o"
	@echo "... intermediate/TreeWalker.i"
	@echo "... intermediate/TreeWalker.s"
	@echo "... main_parser.o"
	@echo "... main_parser.i"
	@echo "... main_parser.s"
	@echo "... main_scanner.o"
	@echo "... main_scanner.i"
	@echo "... main_scanner.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

